general {
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 300
  on-timeout = ~/.config/hypr/scripts/lock_with_checks.sh
}

listener {
  timeout = 330
  on-timeout = ~/.config/hypr/scripts/turn-off-monitors-with-checks.sh
  on-resume = hyprctl dispatch dpms on
}
